version: '3'
services:
   flask:
      build:
         context: ./
         dockerfile: Dockerfile
      command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
      ports:
         - 5000:5000
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PW=211217ns
         - POSTGRES_URL=postgresql
         - POSTGRES_DB
         - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/parsing_site
         - FLASK_APP=app
         - FLASK_ENV=development
      depends_on:
         - postgresql
         - redis
      volumes:
         - .:/app
      links:
        - postgresql

   redis:
      image: redis:latest
      ports:
         - 6379:6379

   celery:
      build: .
      command: celery worker -A app.celery
      environment:
         - DATABASE_URL=postgresql://postgres:211217ns@postgres:5432/parsing_site
         - CELERY_BROKER_URL=redis://redis:6379/0
         - CELERY_RESULT_BACKEND=db+postgresql+psycopg2://postgres:211217ns@postgres:5432/parsing_site
      depends_on:
         - postgresql
         - flask
         - redis

   postgresql:
      image: postgres:latest
      ports:
         - 5432:5432
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=211217ns
         - POSTGRES_DB=parsing_site



