version: '3'
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/parsing_site
      - FLASK_APP=app
      - FLASK_ENV=development
    depends_on:
      - postgresql
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.celery worker
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:211217ns@postgres:5432/parsing_site
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql+psycopg2://postgres:211217ns@postgres:5432/parsing_site
    depends_on:
      - postgresql
      - flask
      - redis

  postgresql:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=211217ns
      - POSTGRES_DB=parsing_site



