version: '3'
services:
  redis:
    image: "redis:alpine"

  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:211217ns@postgres:5432/parsing_site

  celery:
    build: .
    command: celery -A app.celery worker
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=211217ns
      - POSTGRES_DB=parsing_site
    depends_on:
      - postgresql
      - flask
      - redis

  postgresql:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=211217ns
      - POSTGRES_DB=parsing_site