version: '3.7'
services:
   flask:
      build: .
      command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
      ports:
         - "5000:5000"
      environment:
         - FLASK_ENV=development
         - DATABASE_URL=postgresql+psycopg2://postgres:211217ns@postgres:5432/parsing_site
      depends_on:
         - postgres
         - redis
         - celery

   postgres:
      image: postgres:latest
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=211217ns
         - POSTGRES_DB=parsing_site

   redis:
      image: redis:latest

   celery:
      build: .
      command: celery worker -A app.celery --loglevel=INFO
      environment:
         - FLASK_APP=app/app.py
         - DATABASE_URL=postgresql+psycopg2://postgres:211217ns@postgres:5432/parsing_site
         - CELERY_BROKER_URL=redis://redis:6379/0
         - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
         - postgres
         - redis